version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo install process started
      - npm install --force
  build:
    commands:
      - echo build process started now
      - chmod +x devops/buildspec.sh
      - devops/buildspec.sh
      - npm run build
  post_build:
    commands:
      - echo build process finished, we should uplload to S3 now and invalidate cloudfront cache
      - cd dist
      - ls -la
      - aws s3 sync . s3://$TF_VAR_ENV_APP_FE_S3_BUCKET_NAME --delete
      - distribution_id=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items[?@ == '$TF_VAR_ENV_APP_FE_S3_BUCKET_NAME']].Id | [0]" --output text)
      - aws cloudfront create-invalidation --distribution-id $distribution_id --paths "/*"

